Schedule/urls.py
from django.conf.urls import url
from . import views
from django.shortcuts import render
from django.urls import path

app_name = 'Schedule'
urlpatterns = [
    path('sched_add/', views.sched_add, name='sched_add'),
    path('sched_add_save/<int:id>', views.sched_add_save, name='sched_add_save'),
    path('sched_edit/<int:id>', views.sched_edit, name='sched_edit'),
    path('sched_view/', views.sched_view, name='sched_view_all'),
    path('sched_view/<int:id>', views.sched_display, name='sched_view'),
    path('sched_delete/<int:pk>', views.sched_delete, name='sched_delete'),
]

praktikum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.core.exceptions import ImproperlyConfigured
from django.conf.urls.static import static
from django.conf import settings
import os


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_4.urls')),
	path('Schedule/', include('Schedule.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

story_4/urls.py
from django.urls import path
from django.shortcuts import render
from .views import *
from story_4 import views

urlpatterns = [
    path('', views.index, name='home'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
	path('gallery', views.gallery, name='gallery')
]

Schedule/models.py
from django.db import models
import datetime

# Create your models here.
CATEGORY=[('Quiz' , 'Quiz'),
            ('Exam','Exam'),
            ('Homework', 'Homework'),
            ('Hangout','Hangout'),
            ('Meeting', 'Meeting'),
            ('Others', 'Others')]

class Schedule(models.Model):
    title = models.CharField(max_length=100)
    day = models.CharField(max_length=100)
    date = models.DateField()
    time = models.TimeField()
    location = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=CATEGORY)
    description = models.CharField(null=True, max_length=100)

story_4/models.py
from django.db import models

# Create your models here.

Schedule/forms.py
from django import forms
from .models import Schedule
from django.forms import ModelForm

class ScheduleForm(ModelForm):
    class Meta:
        model = Schedule
        fields = ['title','day','date','time','location','category','description']
        labels = {'title':'Title','day':'Day','date':'Date','time':'Time','location':'Location','category':'Category','description':'Description'}
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control','type':'text'}),
            'day':forms.TextInput(attrs={'class':'form-control','type':'text'}),
            'date':forms.DateInput(attrs={'class':'form-control','type':'date'}),
            'time':forms.TimeInput(attrs={'class':'form-control','type':'time'}),
            'location':forms.TextInput(attrs={'class':'form-control','type':'text'}),
            'category':forms.Select(attrs={'class':'form-control'}),
            'description':forms.Textarea(attrs={'class':'form-control','type':'textarea','row':'10'}),
            }

Schedule/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .forms import ScheduleForm
from .models import Schedule
from django.shortcuts import redirect
import datetime


# Create your views here.
def sched_add(request):
    if request.method == "POST":
        form = ScheduleForm(request.POST)
        print(form.is_valid())
        print(form.errors)
        if form.is_valid():
            response = {}
            response['title'] = request.POST['title']
            response['day'] = request.POST['day']
            response['date'] = request.POST['date']
            response['time'] = request.POST['time']
            response['location'] = request.POST['location']
            response['category'] = request.POST['category']
            response['description'] = request.POST['description']
            sched_item = Schedule(title=response['title'], day=response['day'],date=response['date'],time=response['time'],location=response['location'],category=response['category'],description=response['description'])
            sched_item.save()
            return redirect(reverse('Schedule:sched_add'))
    else:
        form = ScheduleForm()
    return render(request, 'ScheduleForm.html', {'title':'Schedule Form','form': form})


def sched_add_save(request, id=None):
    item = Schedule.objects.get(id=id)
    if request.method == "POST":
        form = ScheduleForm(request.POST, instance=item) 
        if form.is_valid():
            form.save()
            return redirect(reverse('Schedule:sched_add_save'))
    else:
        form = ScheduleForm(instance=post)
        return redirect(reverse('Schedule:sched_view'))
    #return render(request, 'Schedule/jadwal_form.hrml', {'form': form})


def sched_edit(request, id=id):
    item = Schedule.objects.get(id=id)
    form = ScheduleForm(instance=item)
    return render(request, 'sched_edit.html', {'title':'Schedule Form','form':form,'item':item})


def sched_view(request):
    data = Schedule.objects.all()
    return render(request, 'sched_view.html', {'data': data})


def sched_display(request, id=id):
    item = Schedule.objects.get(id=id)
    return render(request, 'sched_display.html', {'item':item})


def sched_delete(request, pk):
    Schedule.objects.filter(pk = pk).delete()
    db_item = Schedule.objects.all()
    content = {'title':'Schedule', 'db_item':db_item}
    return redirect('/Schedule/sched_view/')

story_4/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def gallery(request):
    content = {'title' : gallery}
    return render(request, 'gallery.html',content)

def contact(request):
    content = {'title' : contact}
    return render(request, 'contact.html',content)

def about(request):
    content = {'title' : about}
    return render(request, 'about.html',content)

Schedule/templates/Schedule.html
{% extends "jadwal/base.html" %}
{% block content %}
<h1>{{ Schedule.title }}</p>
<p>{{ Schedule.day }}</p>
<p>{{ Schedule.date }}</p>
<p>{{ Schedule.time }}</p>
<p>{{ Schedule.location }}</p>
<p>{{ Schedule.category }}</p>
<p>{{ Schedule.description }}</p>
{% endblock %}

Schedule/templates/ScheduleForm.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1 style = "margin-left: 120px; margin-top: 30px; font-family: Roboto; color: black;">My Daily Activity</h1>
	<div class = "container" style = "margin-top:120px">
	<div class="row">
    <div class="col-sm-6">
		<form action="{% url 'Schedule:sched_add' %}" method="POST">
			{% csrf_token %}
			<div class = "form-group">
				<label for = "title">{{ form.title.label_tag }}</label>
				{{ form.title }}
			</div>
			<div class = "form-group">
				<label for = "day">{{ form.day.label_tag }}</label>
				{{ form.day }}
			</div>
			<div class = "form-group">
				<label for = "date">{{ form.date.label_tag }}</label>
				{{ form.date }}
			</div>
			<div class = "form-group">
				<label for = "time">{{ form.time.label_tag }}</label>
				{{ form.time }}
			</div>
			<div class = "form-group">
				<label for = "location">{{ form.location.label_tag }}</label>
				{{ form.location }}
			</div>
			<div class = "form-group">
				<label for = "category">{{ form.category.label_tag }}</label>
				{{ form.category }}
			</div>
			<div class="form-group">
				<label for = "description">{{ form.description.label_tag }}</label>
				{{ form.description }}
			</div>
			<a href="{% url 'Schedule:sched_add' %}"><button type = "submit" class = "btn btn-primary">OK</button></a>
			<a href="{% url 'Schedule:sched_view_all' %}"><button type = "button" class="btn btn-primary"> View </button></a>
		</form>
    </div>

	</div>
	</div>
{% endblock %}

Schedule/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{% static 'story_4/css/style.css'%}">
		<title>Personal Website</title>
	</head>
	<body background="{% static 'story_4/background.jpg' %}" no-repeat;>
	
	<header class="site-headers">
			<div class="menu">
				<a  href="{% url 'home' %}">Home</a>
				<a  href="{% url 'gallery' %}">Gallery</a>
				<a  href="{% url 'about' %}">About Me</a>
				<a  href="{% url 'contact' %}">Contact</a>
				<a href="{% url 'Schedule:sched_add' %}">Activity</a>
			</div>
	</header>
{% block content %}
{% endblock %}	
	</body>
</html>

Schedule/templates/sched_display.html
{% extends "base.html" %}
{% load static %}

{% block title %}
	{{ data_item.title }}
{% endblock %}

{% block content %}
<br/>
<br/>
<br/>
		<div class = "sched_display" style = "color: white; text-align: center; font-family:'Roboto'; font-weight: bold; padding: 50px;">
			<div class = "single-content">
				<div class = "p-3 bd-highlight"><h2>{{ item.category }}</h2></div>
	        	<div class = "p-3 bd-highlight"><h3><strong>{{ item.title }}</strong></h3></div>
				<div class = "p-3 bd-highlight"><h5>Day:<br/>{{ item.day }}</h5></div>
				<div class = "p-3 bd-highlight"><h5>Date and Time:<br/>{{ item.date }}, {{ item.time }}</h5></div>
				<div class = "p-3 bd-highlight"><h5>Location:<br/>{{ item.location }}</h5></div>
	        	<div class = "p-2 bd-highlight"></p>Description:<br/>{{ item.description }}</p></div>
	        </div>
        	<a href="{% url 'Schedule:sched_delete' pk=item.pk %}"><button type="button" class="btn btn-danger"> Delete </button></a>
        	<a href="{% url 'Schedule:sched_edit' id=item.pk %}"><button type="button" class="btn btn-primary">Edit</button></a>
        	<a href="{% url 'Schedule:sched_view_all' %}"><button type="button" class="btn btn-primary"> Back </button>
        	<br/>
			<br/>
			<br/>
    	</div>
{% endblock %}

Schedule/templates/sched_edit.html
{% extends "base.html" %}
{% load static %}
{% block content %}
	<h1 style = "text-align: center; font-family: Roboto">My Daily Activity</h1>
	<div class = "container" style = "margin-top:120px">
	<div class="row">
    <div class="col-sm-6">
		<form action="{% url 'Schedule:sched_edit_save' id=item.pk%}" method="POST">
			{% csrf_token %}
			<div class = "form-group">
				<label for = "title">{{ form.title.label_tag }}</label>
				{{ form.title }}
			</div>
			<div class = "form-group">
				<label for = "day">{{ form.day.label_tag }}</label>
				{{ form.day }}
			</div>
			<div class = "form-group">
				<label for = "date">{{ form.date.label_tag }}</label>
				{{ form.date }}
			</div>
			<div class = "form-group">
				<label for = "time">{{ form.time.label_tag }}</label>
				{{ form.time }}
			</div>
			<div class = "form-group">
				<label for = "location">{{ form.location.label_tag }}</label>
				{{ form.location }}
			</div>
			<div class = "form-group">
				<label for = "category">{{ form.category.label_tag }}</label>
				{{ form.category }}
			</div>
			<div class="form-group">
				<label for = "description">{{ form.description.label_tag }}</label>
				{{ form.description }}
			</div>
			<a href="{% url 'Schedule:sched_add' %}"><button type = "submit" class = "btn btn-primary">Save</button></a>
			<a href="{% url 'Schedule:sched_view_all' %}"><button type="button" class="btn btn-primary"> View </button>
		</form>
    </div>
	</div>
	</div>
{% endblock %}

Schedule/templates/sched_view.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<br/>
<br/>
<br/>
	<div class = "sched_view">
        <h2 style = "color: black; text-align: center; font-family: Roboto">View My Daily Activity</h2>
		<div class = "container list-group" style = "margin-top:120px; padding:20px">
		<div class = "row">
		<div class = "col-sm-12">
        	{% for item in data %}
		  	<a href = "/Schedule/sched_view/{{ item.id }}" class = "list-group-item list-group-item-action flex-column align-items-start" 
			style = "color: white; background-color: #778899; font-family:'Roboto'; ">
		  		<h3 class = "mb-1">{{ item.title }}</h3>
		  		<p class = "mb-1">{{ item.category }}</p>
				<p class = "mb-1">{{ item.location }}</p>
		  		<p class = "mb-1">{{ item.day }}, {{ item.date }}, {{ item.time }}.</p>
		  		<a href="{% url 'Schedule:sched_delete' pk=item.pk %}"><button type="button" class="btn btn-success btn-sm" style = "float: left">Finish</button></a>
				<br/>
				<br/>
		  	</a>
		  	{% endfor %}
		</div>
		</div>
		</div>
	</div>
{% endblock %}

story_4/templates/about.html
{% extends 'base.html' %}

{% block content %}
	<section>
			<div class="box">
				<h2>Coming Soon</h2>
				</div>
	</section>
{% endblock %}

story_4/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{% static 'story_4/css/style.css'%}">
		<title>Personal Website</title>
	</head>
	<body background="{% static 'story_4/background.jpg' %}" no-repeat;>
	
	<header class="site-headers">
			<div class="menu">
				<a  href="{% url 'home' %}">Home</a>
				<a  href="{% url 'gallery' %}">Gallery</a>
				<a  href="{% url 'about' %}">About Me</a>
				<a  href="{% url 'contact' %}">Contact</a>
				<a href="{% url 'Schedule:sched_add' %}">Activity</a>
			</div>
	</header>
{% block content %}
{% endblock %}	
	</body>
</html>

story_4/templates/contact.html
{% extends 'base.html' %}

{% block content %}
	<section>
			<div class="box">
				<h2>Coming Soon</h2>
				</div>
	</section>
{% endblock %}

story_4/templates/gallery.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<hr/>	
	<main>
		<div class="boxx"><img src="{% static 'story_4/img/1.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/2.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/3.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/4.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/5.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/6.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/7.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/8.jpg' %}"></div>
		<div class="boxx"><img src="{% static 'story_4/img/.9jpg' %}"></div>
	</main>
{% endblock %}

story_4/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<section>
			<div class="box">
				<img src="{% static 'story_4/profil.jpg' %}" alt="" class="box-img">
				<h2>Vikih Fitrianih</h2>
				<h5>Student - Information System</h5>
				<p>I'm a Student at Faculty of Computer Science of Universitas Indonesia. I like a challenges and something new. that so interesting.</p>
			</div>
	</section>
{% endblock %}	